language: node_js

node_js:
  - "node"

addons:
  postgresql: "9.3"

install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create schema test;' -U postgres -d travis_ci_test
  - npm install gulp-cli -g
  - npm install eslint -g
  - npm install babel-cli -g
  - npm install babel-eslint -g
  - npm install mocha -g
  - npm install

env:
  - NODE_ENV=test

script:
  - gulp lint
  - npm test
